version: "3"
services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
  postgres:
    image: postgres:9.5.3
    ports:
      - 5432:5432

